### ISSUE TITLE
Windows support [$30]

### ISSUE THREAD

**Issue by mappu** [SFTtech/openage#9] opened 2014-10-27 03:38 UTC
Windows should be a major supported target either by native compilation or cross-compilation.

Openage currently builds fine under Win32 with some minor patches ( http://i.imgur.com/Hxpym3K.jpg ) but there is no documentation available or binaries. I'll document the steps i used to build for win32 below:
##

**Comment by burgerga** [comment] 2015-01-21 21:16
@TheJJ Just for clarification, is the solution by @mappu in the right direction, and needs to be properly integrated into CMake? Or is there a different issue?

**Comment by TheJJ** [comment] 2015-01-21 23:33
@burgerga The direction seems to be ok. Yes, it should be integrated into CMake properly and the plattform-specific switches should happen in `cpp/crossplattform`. Using mingw64 is probably the ideal way for us I hope.

**Comment by franciscod** [comment] 2015-02-04 08:28
I'm giving a shot on this one, under a W7 32bit VM. Wish me luck!

**Comment by franciscod** [comment] 2015-02-04 10:08
```
Windows@Windows-PC MINGW32 ~/openage
$ buildsystem/simple
...LOTS OF WARNINGS...
...NO ERRORS. END OF OUTPUT!
Windows@Windows-PC MINGW32 ~/openage
$ ls
assets  building.md  CMakeLists.txt  copying.md  development.md  doc  legal     milestones.md  openage_version  README.md  tasks.md
bin     buildsystem  configure       cpp         dist            etc  Makefile  openage.exe    py               status.md

Windows@Windows-PC MINGW32 ~/openage
$ md5sum openage.exe
077383267a3ab0ce1d0d67b5430e7caf *openage.exe

Windows@Windows-PC MINGW32 ~/openage
$ openage
bash: openage: command not found

Windows@Windows-PC MINGW32 ~/openage
$ openage.exe
bash: openage.exe: command not found

Windows@Windows-PC MINGW32 ~/openage
$ ./openage.exe
MSG   launching engine with data directory './assets'
MSG   initialized SDL audio subsystems.
MSG   ERROR: Error opening audio device: DirectSoundCreate: No audio device found
FATAL Exception: Error opening audio device: DirectSoundCreate: No audio device found

Windows@Windows-PC MINGW32 ~/openage
$ MFW
bash: MFW: command not found

```
Windows@Windows-PC MINGW32 ~/openage
$
```

**Comment by franciscod** [comment] 2015-02-04 10:52
Here's my hacky work so far. https://github.com/franciscod/openage/compare/windows

After converting successfully all the media:

```
Windows@Windows-PC MINGW32 ~/openage
$ ./openage.exe

Windows@Windows-PC MINGW32 ~/openage
$
```

it opens and closes: its window blinks, no console output... hmmmmm... ideas?

**Comment by franciscod** [comment] 2015-02-04 10:58
Here is what I did, step by step:

This was on a Windows7 32bit VM.

Also, I really got confused with the msys2/mingw32/mingw64 different shells and packages. Please someone throw some light here :D

- Get AoE2 files.
- Install [msys2](https://msys2.github.io/) on C:\msys2. `/` is now that dir, and `~` is `/home/<username>`.

From now on, you need to use mingw32_shell.bat from C:\msys2.
- `pacman -Syu`
- Move AoE2 directory to ~, assuming "~/age2/Data" is the right directory (contains a lot of dat an drs).
- copypasta this package installing havoc:
```
pacman -S git tar wget mingw-w64-i686-gcc,pkg-config,openssl,libogg,opus,make,python3,SDL2,SDL2_image,glew,freetype,ftgl,opus-tools,python3-numpy,python3-Pillow}
```
- copy mingw32-make to make:
```
cp /mingw32/bin/{mingw32-,}make.exe
```
- compile and install opusfile:
```
wget http://downloads.xiph.org/releases/opus/opusfile-0.6.tar.gz
tar xvf opusfile-0.6.tar.gz
cd opusfile-0.6
./configure --prefix=/mingw32/ --{build,host,target}=i686-w64-mingw32
make install
```
- get and compile openage:
```
cd ~
git clone https://github.com/franciscod/openage/windows
./configure --mode=debug --raw-cmake-args -DOPUSFILE_INCLUDE_DIR=/mingw32/include/opus
cp -R .bin/gcc-debug-O1/ ./bin
buildsystem/simplebuild
```
- you might need to install dejavu serif from http://sourceforge.net/projects/dejavu/files/dejavu/2.34/dejavu-fonts-ttf-2.34.zip
- convert dat *ass*ets:
```
PYTHONPATH=py python3 -m openage.convert -v media -o "assets/converted" "/c/Program Files (x86)/Age of Empires/" graphics:*.* terrain:*.* sounds0:*.* sounds1:*.* gamedata0:*.* gamedata1:*.* gamedata2:*.* interface:*.*
```
- runs without errors, but closes instantly. you can see the window blinking:
```
./openage.exe
```

**Comment by franciscod** [comment] 2015-02-04 11:02
Also, all the `buildsystem/simple` tweaking is because of I was following mappu's guide when I struck this error while running `make`:
```
make[3]: *** No rule to make target '../../py/openage/convert/cabextract/lzxd/pyinterface.cpp', needed by 'py/timefile'.  Stop.
CMakeFiles/Makefile2:959: recipe for target 'CMakeFiles/pymodules.dir/all' failed
```

ideas on this?

**Comment by EvilPeanut** [comment] 2015-02-04 12:02
Good work @franciscod. I don't suppose you would mind zipping and sending me the compiled windows files for openage do you? If so it would be greatly appreciated. My email is reece@amentrix.com

**Comment by franciscod** [comment] 2015-02-04 12:20
PROTIP: `setbuf(stdout, NULL);` is very useful :dancer: 

@EvilPeanut nope, the compiled files doesn't work at all :D if you want the binaries just follow my instructions; this is far from finished.

**Comment by franciscod** [comment] 2015-02-04 12:27
holy crap, i've been debugging 2 hours for THISS!!!!!

``` 
MSG   ERROR: failed reading the file ./assets/converted/termcolors.docx
FATAL Exception: failed reading the file ./assets/converted/termcolors.docx
```

and i forgot the last step from our god and saviour mappu:
- Convert all *.docx files from CRLF to LF
```find ./assets/converted/ | grep 'docx$' | xargs -n1 sed -rie 's/\r\n/\n/'```

**Comment by franciscod** [comment] 2015-02-04 12:43
# !!!!!!!!!!!!!!!!!!!!!

![1423053695](https://cloud.githubusercontent.com/assets/726447/6040569/1ead4956-ac52-11e4-99bd-1af1d28fbdae.png)

###>be gaben
###>gotta go fast

**Comment by franciscod** [comment] 2015-02-04 12:50
Okay guys: this commit builds and runs!!!
https://github.com/franciscod/openage/tree/a4519112381fe7dd8ceed3377d620dc548064d07

```
Windows@Windows-PC MINGW32 ~/openage
$ git remote -v
fd      https://github.com/franciscod/openage (fetch)
fd      https://github.com/franciscod/openage (push)
origin  https://github.com/SFTtech/openage (fetch)
origin  https://github.com/SFTtech/openage (push)

Windows@Windows-PC MINGW32 ~/openage
$ git status
On branch windows
Your branch is up-to-date with 'fd/windows'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        openage.exe

nothing added to commit but untracked files present (use "git add" to track)

Windows@Windows-PC MINGW32 ~/openage
$ git log -1 --oneline
a451911 windows: buildsystem/simple: linker order black magic

Windows@Windows-PC MINGW32 ~/openage
$
```

**Comment by franciscod** [comment] 2015-02-05 03:03
I think now #207 is **very** close to closing this one :)

**Comment by franciscod** [comment] 2015-02-13 04:18
#207 targets compiling and running from a MSYS2 system, on a windows host

#233 cross compiles using mingw-w64 and runs with wine!

**Comment by burgerga** [comment] 2015-02-13 06:25
Congrats, but beware of the next step: packaging :p

**Comment by IronManMark20** [comment] 2016-01-05 00:56
You should consider using the new Clang support in Visual Studio. That may make some things easier.

**Comment by franciscod** [comment] 2016-01-13 23:47
Necrobumping to the maximum level!

Should we target crosscompiling windows binaries from *nix (using mingw-w64, for example), building on windows hosts (with msys2 and/or visual studio), or both?

**Comment by TheJJ** [comment] 2016-01-13 23:50
I'd say prio `#1` is crosscompiling with mingw-w64, if that works, we can think about `msys2` and then visualstudio.

**Comment by wpbest** [comment] 2016-01-13 23:52
It's still in prerelease. No debugger support.

On Monday, January 4, 2016, Ethan <notifications@github.com> wrote:

> You should consider using the new Clang support in Visual Studio. That may
> make some things easier.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SFTtech/openage/issues/9#issuecomment-168858135>.
>


-- 
William P. Best
11125 S Dartmoor Ct
Parker, CO, 80138-7309
Cell: 720.366.7270
Work: 303.328-6468

**Comment by burgerga** [comment] 2016-01-14 08:04
One of the main problems now is packaging, and mainly the question what to do with the python interpreter. If you want to include that in the package it's quite annoying, I think there are only nice solutions for python 2 but i could be wrong...

**Comment by zuntrax** [comment] 2016-01-24 10:13
@burgerga I ran into some problems myself trying to package it for nixos. We will probably redesign some of the python-specific parts. Shipping an interpreter in the openage package will probably cause a lot of problems.

**Comment by franciscod** [comment] 2017-11-15 19:29
Ho, I remember trying to crosscompile with mingw-w64 from Arch Linux and hit some roadblocks with the mingw-w64 Python package. It's been updated to 3.6 now, just letting you know if someone wants to give it a shot :)

https://aur.archlinux.org/packages/mingw-w64-python

**Comment by simonsan** [comment] 2019-06-17 04:06
There is a 64-bit installer out for windows 10. You can download it here.
https://github.com/SFTtech/openage/releases

Next step could be reproducible and frequent CI-builds with Kevin.
I don't know when this topic can be closed - Windows support could take forever. :-D

**Closed** 2019-06-20 10:44 UTC
Labels: windows

**Comment by simonsan** [comment] 2019-07-26 17:40
Bookmarking [one relevant commit (probably not fast-forward)](https://github.com/tusharpm/openage/commit/12952660f2be22b7f697772b703728ec97d11922) to build openage under windows with mingw (by @tusharpm).
