### ISSUE TITLE
Rendering Glitch: Purple Trees

### ISSUE THREAD

**Issue by ghost** [SFTtech/openage#359] opened 2015-08-23 22:10 UTC
Running Mesa 11.0-git, Arch Linux 64bit, MATE, AMD Radeon HD 7750.

I don't remember trees being this purple in the original game. Most likely a Mesa bug.

![Purple Trees](http://i.imgur.com/M3hdd6j.png)
##

**Comment by TheJJ** [comment] 2015-08-23 22:33
Will be addressed in #287, i'll implement outline rendering properly which should fix this.

**Comment by heinezen** [comment] 2017-10-02 16:59
Could be caused by the original textures. Apparently "pink = transparency" is a feature of the Genie engine according to Matt Pritchard.

> In our art tools, and renderings. Transparency was always color index 255, and viewed as pink (RGB 255, 0, 255)

[Source](http://aok.heavengames.com/cgi-bin/aokcgi/display.cgi?action=st&fn=3&tn=40110&st=38#post39)

**Comment by sandsmark** [comment] 2017-11-12 13:45
possibly this: https://github.com/SFTtech/openage/blob/master/assets/shaders/teamcolors.frag.glsl#L49

**Comment by TheJJ** [comment] 2017-11-13 15:57
Can anyone try to reproduce and change the color in the shader?

**Comment by heinezen** [comment] 2017-11-14 18:07
Can confirm that @sandsmark is right. When set to this:

`pixel = vec4(0.0/255.0, 0.0/255.0, 0.0/255.0, 1.0);`

Trees are no longer pink.

![openage_2017-11-14_19-04-34_00](https://user-images.githubusercontent.com/6852422/32796394-ebe0fde6-c96e-11e7-94f6-4de00c4947c7.png)

**Comment by heinezen** [comment] 2017-11-18 19:25
On second thought, this might be a player colour that is reserved for Gaia. Gaia objects are only supposed to show outlines when a villager interacts with them. The outline of a Gaia object then gets assigned the same colour as the player colour of the villager.

**Comment by heinezen** [comment] 2024-01-21 05:09
Pink trees should be a relic of past development by now.

**Closed by heinezen** 2024-01-21 05:09 UTC
Labels: bug, area: renderer, lang: c++
