### ISSUE TITLE
coord test uses nonexistant opengl context on Mac OS X

### ISSUE THREAD

**Issue by darrenstrash** [SFTtech/openage#383] opened 2015-09-16 09:49 UTC
**System setup:**
Mac OS X Yosemite 10.10.4 (14E46)
Using g++ version 5.2.0

[ 8/19] cpp coord::tests::coord
INFO Font queried: DejaVu Sans Mono:style=Book
INFO Font file: /Users/strash/Library/Fonts/DejaVuSansMono.ttf

**SIGSEGV**

**FATAL:** terminate has been called

current stack

Traceback (most recent call last):
  File ?, in openage::error::StackAnalyzer::analyze()+0x77 [0x1099a153b]

standard terminate handler

**Comment by TheJJ** [comment] 2015-09-16 09:51
Can you build again in debug mode (`./configure --compiler clang --mode debug`) and run this again or in `gdb` so we can see the backtrace?

**Comment by darrenstrash** [comment] 2015-09-16 11:30
Sure, here it is.

INFO Font queried: DejaVu Sans Mono:style=Book
INFO Font file: /Users/strash/Library/Fonts/DejaVuSansMono.ttf
Process 56514 stopped
* thread #1: tid = 0x329394, 0x00007fff917d2a47 libGL.dylib`glGetIntegerv + 18, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x348)

    frame #0: 0x00007fff917d2a47 libGL.dylib`glGetIntegerv + 18
libGL.dylib`glGetIntegerv:
->  0x7fff917d2a47 <+18>: movq   0x348(%rdx), %rax
    0x7fff917d2a4e <+25>: movq   (%rdx), %rdi
    0x7fff917d2a51 <+28>: movl   %ecx, %esi
    0x7fff917d2a53 <+30>: movq   %r8, %rdx

(lldb) bt
* thread #1: tid = 0x329394, 0x00007fff917d2a47 libGL.dylib`glGetIntegerv + 18, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x348)
  * frame #0: 0x00007fff917d2a47 libGL.dylib`glGetIntegerv + 18

    frame #1: 0x00000001006491b0 libftgl.2.dylib`FTTextureFontImpl::CreateTexture() + 54

    frame #2: 0x0000000100648b38 libftgl.2.dylib`FTTextureFontImpl::MakeGlyphImpl(FT_GlyphSlotRec_*) + 160

    frame #3: 0x0000000100645504 libftgl.2.dylib`FTFontImpl::CheckGlyph(unsigned int) + 92

    frame #4: 0x00000001006450d1 libftgl.2.dylib`FTFontImpl::Advance(char const*, int, FTPoint) + 137

    frame #5: 0x0000000100644472 libftgl.2.dylib`FTFont::Advance(char const*, int, FTPoint) + 40

    frame #6: 0x0000000100251ac4 libopenage.dylib`openage::console::Console::Console(this=0x00007fff5fbff070) + 340 at console.cpp:36

    frame #7: 0x000000010025b732 libopenage.dylib`openage::coord::tests::camhud_0() + 846 at tests.cpp:560

    frame #8: 0x000000010025b9d4 libopenage.dylib`openage::coord::tests::coord() + 64 at tests.cpp:616

    frame #9: 0x00000001002fe9dd libopenage.dylib`openage::testing::run_method(name=0x00007fff5fbff3b0) + 201 at testlist.gen.cpp:103

    frame #10: 0x000000010254513d cpp_testing.so`__pyx_pf_7openage_7testing_11cpp_testing_run_cpp_method(__pyx_self=<unavailable>, __pyx_v_methodname=<unavailable>) + 1207 at cpp_testing.cpp:751

    frame #11: 0x00000001025452ce cpp_testing.so`__pyx_pw_7openage_7testing_11cpp_testing_1run_cpp_method(__pyx_self=0x0000000000000000, __pyx_v_methodname=0x0000000102480e40) + 83 at cpp_testing.cpp:700

    frame #12: 0x00000001000ab9ad Python`PyEval_EvalFrameEx + 18389

    frame #13: 0x00000001000a7029 Python`PyEval_EvalCodeEx + 1593

    frame #14: 0x00000001000aeadb Python`fast_function + 321

    frame #15: 0x00000001000ab6fa Python`PyEval_EvalFrameEx + 17698

    frame #16: 0x00000001000aea65 Python`fast_function + 203

    frame #17: 0x00000001000ab6fa Python`PyEval_EvalFrameEx + 17698

    frame #18: 0x00000001000a7029 Python`PyEval_EvalCodeEx + 1593

    frame #19: 0x0000000100035fb5 Python`function_call + 372

    frame #20: 0x0000000100006d93 run`PyInit_run + 136 at run.cpp:1142

    frame #21: 0x0000000100006d0b run`PyInit_run [inlined] __Pyx_PyObject_CallNoArg(func=0x000000010220c6a8) + 288

    frame #22: 0x0000000100006beb run`PyInit_run + 1666

    frame #23: 0x0000000100007278 run`__Pyx_main(argc=3, argv=0x0000000100d0c350) + 68 at run.cpp:1407

    frame #24: 0x000000010000743f run`main(argc=3, argv=0x00007fff5fbffad8) + 325 at run.cpp:1548

    frame #25: 0x00007fff8aac85c9 libdyld.dylib`start + 1

    frame #26: 0x00007fff8aac85c9 libdyld.dylib`start + 1

**Comment by jprashanth** [comment] 2015-09-16 14:51
Duplicate of #354

**Comment by TheJJ** [comment] 2015-09-16 15:05
Although your issue is the older one, i'd leave this one open as we have way more info in here by now.

**Comment by jprashanth** [comment] 2015-09-16 15:06
Yes, Definitely.

**Closed** 2015-11-06 23:18 UTC
Labels: bug, c++, os x
