### ISSUE TITLE
Incorrect unit animation speeds

### ISSUE THREAD

**Issue by ghost** [SFTtech/openage#283] opened 2015-04-17 22:23 UTC
I've messed around with the latest revision of openage, and it seems that the idle animation of GENITX is too fast. Not sure if this unit is used in the original game.

Probably it would be best adding some timing infrastructure or patch the wrong times in the convert script.

@Jon0 is probably the best guess for fixing this.
##

**Comment by Jon0** [comment] 2015-04-19 12:01
There are some rate multiplier values in game data, I havent fully worked out how they are used.

**Comment by TheJJ** [comment] 2015-08-16 19:10
It may be fixed by now. Also, i think the issue is not a too fast animation, but rather a missing pause between playing those animations.

**Comment by heinezen** [comment] 2023-09-08 21:37
This is obsolete with the new renderer

**Closed by heinezen** 2023-09-08 21:37 UTC
Labels: bug, lang: c++
