### ISSUE TITLE
Build failed on macOS: Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by baijifeilong** [SFTtech/openage#1027] opened 2018-06-14 05:11 UTC
Scanning dependencies of target nyancat
[ 98%] Building CXX object nyan/CMakeFiles/nyancat.dir/nyan_tool.cpp.o
[100%] Linking CXX executable nyancat
Undefined symbols for architecture x86_64:
  "nyan::Number<long long>::apply_value(nyan::Value const&, nyan::nyan_op)", referenced from:
      vtable for nyan::Number<long long> in nyan_tool.cpp.o
  "nyan::Number<long long>::allowed_operations(nyan::Type const&) const", referenced from:
      vtable for nyan::Number<long long> in nyan_tool.cpp.o
  "nyan::Number<long long>::str() const", referenced from:
      vtable for nyan::Number<long long> in nyan_tool.cpp.o
  "nyan::Number<long long>::copy() const", referenced from:
      vtable for nyan::Number<long long> in nyan_tool.cpp.o
  "nyan::Number<long long>::hash() const", referenced from:
      vtable for nyan::Number<long long> in nyan_tool.cpp.o
  "nyan::Number<long long>::repr() const", referenced from:
      vtable for nyan::Number<long long> in nyan_tool.cpp.o
  "nyan::Number<long long>::equals(nyan::Value const&) const", referenced from:
      vtable for nyan::Number<long long> in nyan_tool.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [nyan/nyancat] Error 1
make[1]: *** [nyan/CMakeFiles/nyancat.dir/all] Error 2
make: *** [all] Error 2

**Comment by TheJJ** [comment] 2018-06-14 10:54
Duplicate of SFTtech/nyan#50.

**Closed by TheJJ** 2018-06-14 10:54 UTC
