### ISSUE TITLE
VMs for testing on Windows

### ISSUE THREAD

**Issue by momo-aux** [SFTtech/openage#931] opened 2017-11-06 08:22 UTC
Hi, I think you could use https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ for this.

Free and usable for 90 Days, then reset, repeat.

**Comment by iNaKoll** [comment] 2017-11-06 10:48
Hi,

The license for this "IE/Edge Windows VM" is granted by microsoft for "testing purposes only", non-commercial use, 90-days, one computer hardware and one person (no support, no warranty and no activation).

Nice

**Comment by TheJJ** [comment] 2017-11-13 15:52
Great idea! We should probably use a qemu memory snapshot to speed up the boot process. And we'd need to install `ssh` and `python` there, with the linux subsystem this shouldn't be hard (i've never used it so far).

**Comment by zuntrax** [comment] 2018-01-10 01:26
Of all the folks with SSH access to our CI infrastructure, I arguably have the highest tolerance to managing Windows machines. Looks like a task for me.
Fun fact: Those modern.ie VMs come with openssh-server preconfigured and running.
* [ ] change storage to virtio
* [ ] change passwords, host keys, etc.
* [ ] disable wuauserv
* [ ] install git
* [ ] install cmake
* [ ] install VS2017
* [ ] install vcpkg
* [ ] build deps in vcpkg
* [ ] install python
* [ ] install python modules
* [ ] install opus-tools
* [ ] do a test build
* [ ] commit qcow2 snapshot
* [ ] patch kevin (and chantal) to work with Windows
* [ ] add windows vm to falk.conf
* [ ] configure windows-specific kevinfile in kevin.conf
* [ ] write kevinfile for openage windows builds
* [ ] think of more stuff i forgot...

**Comment by janisozaur** [comment] 2018-01-10 10:36
@zuntrax you can probably mark half of your list done if you use the MSVC VM instead: https://developer.microsoft.com/en-us/windows/downloads/virtual-machines

**Comment by zuntrax** [comment] 2018-01-10 16:41
@janisozaur I had a look at that one, too, but I didn't like the fixed expiration date. Also, we are somewhat limited on storage space on the CI server, and the MSVC VM comes with a lot of unnecessary stuff preinstalled. Also I'm mostly done with the generic stuff. Right now, I'm waiting for the qt5 archive to be extracted.

**Comment by zuntrax** [comment] 2018-01-12 21:49
Still stuck on qt5. Installation reproducibly fails with both x86-windows and x64-windows in clean vcpkg clones during packaging of the debug build. Also the new VCPKG_BUILD_TYPE variable is not yet honored by the custom cmake functions used for building qt5, trying to fix that right now. This would give me a fast workaround, since the release build works fine.

**Comment by zuntrax** [comment] 2018-03-11 13:29
This will be handled in another repo. First PR will come soon:
https://github.com/SFTtech/kevin-win-setup

**Comment by simonsan** [comment] 2019-04-28 09:11
Hey there @zuntrax, any news on this one?

**Comment by Jogai** [comment] 2019-04-29 10:38
Seems like a job for docker/vagrant, here is a template that uses the latest dev image from ms: https://github.com/gusztavvargadr/packer/#development

**Comment by simonsan** [comment] 2019-06-08 01:51
Getting to it! <3

**Comment by heinezen** [comment] 2023-09-08 21:11
I think the current workflows are close enough to resolving this issue for now. The builds are running fine too :)

**Closed by heinezen** 2023-09-08 21:11 UTC
Labels: os: windows, to-discuss, ci

**Comment by Jogai** [comment] 2023-09-09 08:10
Is the smiley due to the fact that the last release is over 3 years ago?

**Comment by heinezen** [comment] 2023-09-09 13:13
@Jogai No, mostly because I'm happy that Windows builds are working smoothly right now.
