### ISSUE TITLE
Fix HD-edition asset conversion

### ISSUE THREAD

**Issue by zuntrax** [SFTtech/openage#337] opened 2015-07-31 03:38 UTC
Asset conversion for the HD-edition is broken. This consists of two problems.
About a month ago, the asset structure was changed by whoever maintains HD-edition, all `drs` archives are now unpacked, strings now live in `resources/strings`

The other problem is broken code:
http://pastebin.com/CCEQssFq
This can be adressed by changing the listdirs call to a list call on a subdirectory.

To test the second problem without having to take care of the first, one can easily mock an old-style HD-edition installation by removing `language*.dll` and creating `bin/en/en-language.txt` from an existing AoE2 installation.

**Comment by mic-e** [comment] 2015-07-31 08:10
Duplicate of #318

**Comment by mic-e** [comment] 2015-07-31 08:11
I discussed this with @jfeo yesterday, not sure whether he wanted to do it.

**Closed** 2015-08-01 11:57 UTC
Labels: assets, bug, python
