### ISSUE TITLE
Minimise state changes in new renderer

### ISSUE THREAD

**Issue by Vtec234** [SFTtech/openage#1054] opened 2018-10-06 13:30 UTC
### Contributing to the new renderer:
The renderer interface is defined in headers, with the main class in `libopenage/renderer/renderer.h`.
A good place to start looking is `libopenage/renderer/tests.cpp`, which presents a sample usage of the renderer. To run the test, after compiling Openage do `./run test -vd renderer.tests.renderer_demo 0`.

### Required knowledge:
You need to be familiar with how OpenGL modifies its internal
 state when shader programs are switched, different buffers bound, draw calls made, etc.

### What to modify:
1. The logic in `libopenage/renderer/opengl/renderer.cpp` should not simply execute renderables one after another, but rather sort them first - by shader program, then by used buffer. This will require removing some `const`s from `RenderPass` and changing the documentation to specify that the order of `Renderable`s may be changed by the renderer.
3. Documentation should be added to every new header and existing documentation updated to reflect changes.

**Comment by teldosas** [comment] 2019-10-23 08:21
Is this a duplicate of #34 ?

**Comment by Vtec234** [comment] 2019-10-23 18:07
I think what's happened is that I hijacked that thread to list the things to be done for the new renderer in general, while this issue is specifically only about reordering drawables so as to not do many shader/texture/whatever switches. I do agree the initial post in #34 does overlap a bit.

**Closed** 2020-01-17 16:59 UTC
Labels: c++, rendering
