### ISSUE TITLE
Convert PNG Sprite Sheet to Frames In Correct Order

### ISSUE THREAD

**Issue by gregstein** [SFTtech/openage#1209] opened 2019-12-25 14:27 UTC
Hello,

I'm new here but notably impressed with this fantastic library such great work tbh. I just have a question if some of you could help.

I extracted the png file out of smx (AoE2 DE):
`python3 -m openage convert-file --player-palette-file ~/games/aoe2de/Data/playercolor_blue.pal --palette-file ~/games/aoe2de/Data/b_west.pal u_elite_eagle.smx /tmp/rofl.png`

Example:
![rofl](https://user-images.githubusercontent.com/16618729/71447073-bfe83f80-272a-11ea-8829-a583bd28ac3a.png)

Now I'm scratching my head to how to convert this spritesheet into frames so I can edit them one by one.

Thank you,

**Comment by heinezen** [comment] 2019-12-25 16:43
Hey Greg, glad you found us!

Our converter puts the frames into a spritesheet by design. If you want to extract every frame individually, you can start editing here:

https://github.com/SFTtech/openage/blob/7ca1723d486799d9922f36b07d50a920fdc02317/openage/convert/texture.py#L127-L132

This normally puts the frames in a list for packing, but you can replace `frames.append(subtex)` in line 132 with `self.save(self, targetdir, filename, meta_formats=None)` (choose parameters accprding to your needs). This should output each frame one by one.

**Comment by gregstein** [comment] 2019-12-25 16:57
> Hey Greg, glad you found us!
> 
> Our converter puts the frames into a spritesheet by design. If you want to extract every frame individually, you can start editing here:
> 
> https://github.com/SFTtech/openage/blob/7ca1723d486799d9922f36b07d50a920fdc02317/openage/convert/texture.py#L127-L132
> 
> This normally puts the frames in a list for packing, but you can replace `frames.append(subtex)` in line 132 with `self.save(self, targetdir, filename, meta_formats=None)` (choose parameters accprding to your needs). This should output each frame one by one.

Heinezen.. Thank you so much I couldn't be more satisfied with your beautiful answer

**Comment by TheJJ** [comment] 2019-12-26 20:25
So i guess we can close this. If not, please report back :)

**Closed by TheJJ** 2019-12-26 20:25 UTC
Labels: assets, question

**Comment by gregstein** [comment] 2019-12-26 20:41
Hello again,

So i'm struggling with the parameters and how I should run them..

I have tried:

`python3 -m openage convert-file --player-palette-file home/greg/games/aoe2de/Data/playercolor_blue.pal --palette-file /home/greg/games/aoe2de/Data/b_west.pal /home/greg/games /home/greg/rofl.png`

Sorry for being a burden on this one as I am still learning python and making progress day in day out.

Thank you so much

**Comment by heinezen** [comment] 2019-12-26 22:18
The solution is a bit hacky, but it should work. Replace the lines I quoted with this block of code, replace the placeholders for the `Directory` path and compile the project again.

```
frame_ctr = 0
for frame in input_data.main_frames: 
    for subtex in self._smp_to_subtextures(frame, 
                                           main_palette, 
                                           player_palette, 
                                           custom_cutter): 
        self.image_data = TextureImage(subtex)
        frame_name = "frame_%s" % (frame_ctr)
        frame_name += 1
        self.save(Directory(Path("/folder/on/your/system/").parent).root, frame_name)
```

**Comment by gregstein** [comment] 2019-12-26 22:48
I did exactly as you have suggested but im getting "ValueError: Texture image must be created from PIL Image or numpy array, not '<class 'openage.convert.texture.TextureImage'>'"

![texture](https://user-images.githubusercontent.com/16618729/71492694-98cc6380-2839-11ea-9914-8915843621ef.png)

This is the command used:
`python3 -m openage convert-file --player-palette-file /home/greg/game/playercolor_blue.pal --palette-file /home/greg/game/b_west.pal /home/greg/game/u_vil_male_villager_idleA_x1.smx /home/greg/game/rofl.png`

And is it necessary to rebuild as in deleting the project then make it again? Because I only used make command to rebuild.

**Comment by heinezen** [comment] 2019-12-26 23:13
I updated the line with `TextureImage` in my comment above so that it hopefully works now (sorry for the guesswork, I can't test the code myself atm). Using `make` to rebuild is fine and the only thing necessary.

**Comment by gregstein** [comment] 2019-12-26 23:50
That fixed but now I see a new error in your last code edit:

`NameError: name 'Directory' is not defined`
![directory](https://user-images.githubusercontent.com/16618729/71493872-e0a3b880-2842-11ea-8b3c-b30d5474b721.jpg)


I think if this is fixed your code will work

**Comment by heinezen** [comment] 2019-12-26 23:53
Try importing this at the start of the file

```
from ..util.fslike.directory import Directory
```

**Comment by gregstein** [comment] 2019-12-27 00:02
After importing the line i get 
```
raise Exception("incompatible type for path: %s" % type(path_))
Exception: incompatible type for path: <class 'openage.util.fslike.path.Path'>
```
![imcompatible](https://user-images.githubusercontent.com/16618729/71494056-75f37c80-2844-11ea-8f2f-0b006c45ee88.jpg)

**Comment by heinezen** [comment] 2019-12-27 00:09
Removing the `Path(..).parent` expression around the string `"/home/greg/frames/"` might help.

**Comment by gregstein** [comment] 2019-12-27 00:17
Oh I'm sorry about that. I fixed the code as suggested and now... 
```
raise Exception("cannot create texture with empty input frame list")
Exception: cannot create texture with empty input frame list
```

![empty_inputframe](https://user-images.githubusercontent.com/16618729/71494330-a0463980-2846-11ea-955f-c9c981254fdd.jpg)

**Comment by heinezen** [comment] 2019-12-27 00:21
Hmm.. Look in your folder :D

It should have converted the frames individually. The last exception occurs because the frames weren't put in a list at the end. You can fix that by adding `frames.append(subtex)` after `self.save(..)` again.

**Comment by gregstein** [comment] 2019-12-27 00:24
You are one hell of a Genius! Though I got an error that 'can't create texture with empty input frame' Still the frames were extracted successfully. 

Look at this beauty:
![myframes](https://user-images.githubusercontent.com/16618729/71494380-2ebabb00-2847-11ea-98ac-cce45b02597a.jpg)
Fuck Yeah!!

I'm really sorry for all the trouble you went through to help me out with this.

Have an awesome day brother <3

**Comment by gregstein** [comment] 2019-12-27 00:26
> Hmm.. Look in your folder :D
> 
> It should have converted the frames individually. The last exception occurs because the frames weren't put in a list at the end. You can fix that by adding `frames.append(subtex)` after `self.save(..)` again.

How did you know that? LOL... That's insane really you guys are fucking python geniuses and I think studying this library will help me come even little bit closer to being a python mother fucker.
