### ISSUE TITLE
"No module named 'numpy'" when numpy is installed

### ISSUE THREAD

**Issue by Flappaslappa** [SFTtech/openage#680] opened 2016-12-24 05:21 UTC
homebrew is telling me numpy is installed properly 

`Brendans-MBP:~ simon$ brew install numpy --with-python3
Warning: homebrew/python/numpy-1.11.2 already installed`

if i missed something obvious please yell at me

```
-- Looking for suitable Python >=3.4 - Success: /usr/local/bin/python3
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'numpy'
CMake Error at buildsystem/modules/FindPython.cmake:36 (message):
  failed:

  /usr/local/bin/python3 -c 'import numpy; print(numpy.get_include())'

Call Stack (most recent call first):
  buildsystem/modules/FindNumpy.cmake:10 (py_exec)
  buildsystem/HandlePythonOptions.cmake:8 (find_package)
  CMakeLists.txt:69 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/simon/Documents/repos/SFT/openage/.bin/clang++-debug-Oauto-sanitize-none/CMakeFiles/CMakeOutput.log".
Brendans-MBP:openage simon$
```

**Comment by TheJJ** [comment] 2016-12-24 14:45
IT IS NOT A BUG OF OPENAGE IF THE SAME ERROR OCCURS WHEN YOU LAUNCH THE PYTHON3 SHELL AND TYPE `import numpy`.

CAN YOU TRY THAT PLEASE?

(done yelling)

**Comment by Flappaslappa** [comment] 2016-12-25 03:17
ok so i had to python3 -m pip install to get it in the right site-packages folder.
but.. now im getting this.. 
do you think I dun goofed and should just retry from a clean start 

-- Checking utility program opusenc - Success
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
CMake Warning at buildsystem/doxygen.cmake:50 (message):
  doxygen couldn't be found, you won't be able to generate docs
Call Stack (most recent call first):
  CMakeLists.txt:88 (doxygen_configure)

cpp library
	libopenage                                          [213 sources] [15 generated]
CMake Error at libopenage/CMakeLists.txt:90 (find_package):
  By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Core", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Core"
  (requested version 5.4) with any of the following names:

    Qt5CoreConfig.cmake
    qt5core-config.cmake

  Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
  "Qt5Core_DIR" to a directory containing one of the above files.  If
  "Qt5Core" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/Users/simon/Documents/repos/SFT/openage/.bin/clang++-debug-Oauto-sanitize-none/CMakeFiles/CMakeOutput.log".
Brendans-MBP:openage simon$

**Comment by TheJJ** [comment] 2016-12-25 12:44
OK THAT LOOKS BETTER, NOW YOU ARE MISSING THE QT5 COMPONENTS. DID YOU FOLLOW THE [`building.md` GUIDE](https://github.com/SFTtech/openage/blob/master/doc/building.md)?

**Comment by Birch-san** [comment] 2016-12-28 21:33
The error above is the expected behaviour for Mac builds in `master`.

Switch to the [branch from dusek's fork](https://github.com/SFTtech/openage/pull/658) if you want to build successfully on Mac. It has patches for `libopenage/CMakeLists.txt` and `libopenage/gui/guisys/public/gui_renderer.h`.

**Comment by Birch-san** [comment] 2016-12-28 21:35
but please understand that even if you successfully build on Mac: you will not be able to _run_ successfully.

**Comment by TheJJ** [comment] 2017-01-10 17:49
Did you have success now? The Qt location problems should be fixed by now (#684).

**Comment by Flappaslappa** [comment] 2017-01-11 03:34
build was successful! thanks guys
but im getting this after ./run.py 
get the cap-locks queued 

Brendans-MBP:openage-master simon$ ./run.py
Traceback (most recent call last):
  File "./run.py", line 15, in <module>
    main()
  File "/Users/simon/Documents/repos/SFT/openage-master/openage/__main__.py", line 97, in main
    return args.entrypoint(args, cli.error)
  File "/Users/simon/Documents/repos/SFT/openage-master/openage/game/main.py", line 31, in main
    from ..cppinterface.setup import setup
  File "/Users/simon/Documents/repos/SFT/openage-master/openage/cppinterface/setup.py", line 11, in <module>
    from ..log.log_cpp import enable_log_translation
ImportError: No module named 'openage.log.log_cpp'
Brendans-MBP:openage-master simon$

**Comment by zuntrax** [comment] 2017-01-11 10:00
Can you `ls -l openage/log/`, please? `openage.log.log_cpp` is built using cython, so there should be `log_cpp.cpp` and something like `log_cpp.cpython-35m-x86_64-linux-gnu.so`...

**Comment by TheJJ** [comment] 2017-01-12 12:03
I guess you may not actually have built the project with `make`. Did you build it?

**Comment by Birch-san** [comment] 2017-01-12 21:11
Did you follow the build instructions [here](https://github.com/SFTtech/openage/blob/master/doc/building.md#for-installing-on-your-local-system-not-yet-fully-tested)?

```bash
./configure --mode=release --compiler=clang --prefix=/usr
make
```

**Comment by Flappaslappa** [comment] 2017-01-16 07:29
@TheJJ ok, ran make and build is successful! just got to apply game assets.

**Comment by TheJJ** [comment] 2017-01-16 09:17
Okay, nice :)

**Closed by TheJJ** 2017-01-16 09:17 UTC
Labels: buildsystem, mac os, question
